//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class FlociCloudFormationExtensions
    {
        [AspireExportIgnore(Reason = "Aspire.Hosting.AWS CloudFormation and CDK resources are not available in polyglot AppHosts.")]
        public static ApplicationModel.IResourceBuilder<T> WithReference<T>(this ApplicationModel.IResourceBuilder<T> builder, ApplicationModel.IResourceBuilder<ApplicationModel.FlociAwsContainerResource> floci, CommunityToolkit.Aspire.Hosting.Floci.AWS.FlociAwsOptions options, AWS.IAWSSDKConfig? awsConfig = null)
            where T : class, AWS.CloudFormation.ICloudFormationResource { throw null; }

        [AspireExportIgnore(Reason = "Aspire.Hosting.AWS CloudFormation and CDK resources are not available in polyglot AppHosts.")]
        public static ApplicationModel.IResourceBuilder<T> WithReference<T>(this ApplicationModel.IResourceBuilder<T> builder, ApplicationModel.IResourceBuilder<ApplicationModel.FlociAwsContainerResource> floci, string region = "us-east-1")
            where T : class, AWS.CloudFormation.ICloudFormationResource { throw null; }
    }
}

namespace CommunityToolkit.Aspire.Hosting.Floci.AWS
{
    public sealed partial class FlociAwsOptions
    {
        public string AccessKeyId { get { throw null; } set { } }

        public string Region { get { throw null; } set { } }

        public string SecretAccessKey { get { throw null; } set { } }

        public string? SessionToken { get { throw null; } set { } }
    }
}
